// <auto-generated />
namespace MyShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CreateColor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateColor));
        
        string IMigrationMetadata.Id
        {
            get { return "201609300727355_Create-Color"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
